"""Regression suite for the leaf-tab icon resolver (v0.8.0a32+).

``standalone_window._resolve_leaf_icon`` walks an icon-source chain
(tree-node override -> tool's cell-icon) and returns a ``QIcon``.
Tabs in the standalone-tree window use this to display the tool's
icon next to its label.
"""
from __future__ import annotations

import base64
from pathlib import Path

import pytest
from PySide6.QtGui import QIcon, QPixmap
from PySide6.QtWidgets import QApplication, QMessageBox

_app = QApplication.instance() or QApplication([])
QMessageBox.warning = staticmethod(  # type: ignore[assignment]
    lambda *a, **kw: QMessageBox.StandardButton.Ok
)
QMessageBox.information = staticmethod(  # type: ignore[assignment]
    lambda *a, **kw: QMessageBox.StandardButton.Ok
)


def _tiny_png_b64() -> str:
    """Valid 1x1 PNG as base64, generated by Qt itself.

    Hand-crafting a 67-byte PNG is fiddly enough that I got the
    IDAT block lengths wrong on the first attempt and libpng
    rejected it.  Generating via QPixmap.save() guarantees the
    bytes are a libpng-acceptable PNG on whatever Qt build the
    tests are running against.
    """
    from PySide6.QtCore import QBuffer, QByteArray, QIODevice
    from PySide6.QtGui import QPixmap, QColor

    px = QPixmap(1, 1)
    px.fill(QColor("red"))
    buf = QBuffer()
    buf.open(QIODevice.OpenModeFlag.WriteOnly)
    assert px.save(buf, "PNG"), "QPixmap.save(PNG) failed"
    return base64.b64encode(bytes(buf.data())).decode("ascii")


class TestResolveLeafIcon:
    """Confirm each rung of the priority chain works in isolation."""

    def test_node_icon_data_wins(self, tmp_path):
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef

        node = TreeNode(
            type="leaf",
            path="x.scriptree",
            icon_data=_tiny_png_b64(),
            icon_format="png",
        )
        # Tool also has an icon -- but the node override should win.
        tool = ToolDef(
            name="x",
            executable="echo",
            cell_icon="some-nonexistent-bundle-name",
        )
        icon = _resolve_leaf_icon(node, tool, tmp_path / "x.scriptree")
        assert isinstance(icon, QIcon)
        assert not icon.isNull(), (
            "node's embedded icon_data should produce a non-null QIcon"
        )

    def test_tool_cell_icon_data_used_when_node_empty(
        self, tmp_path,
    ):
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef
        node = TreeNode(type="leaf", path="x.scriptree")
        tool = ToolDef(
            name="x",
            executable="echo",
            cell_icon_data=_tiny_png_b64(),
            cell_icon_format="png",
        )
        icon = _resolve_leaf_icon(
            node, tool, tmp_path / "x.scriptree",
        )
        assert not icon.isNull()

    def test_absolute_path_icon_file(self, tmp_path):
        """A non-bundled path (absolute) should be loaded directly."""
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef

        png_path = tmp_path / "custom-icon.png"
        # Write the same minimal PNG bytes to disk.
        png_path.write_bytes(base64.b64decode(_tiny_png_b64()))

        node = TreeNode(type="leaf", path="x.scriptree", icon=str(png_path))
        tool = ToolDef(name="x", executable="echo")
        icon = _resolve_leaf_icon(
            node, tool, tmp_path / "x.scriptree",
        )
        assert not icon.isNull()

    def test_relative_path_resolves_against_tool_dir(
        self, tmp_path,
    ):
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef

        tool_dir = tmp_path / "AppFolder"
        tool_dir.mkdir()
        png = tool_dir / "rel-icon.png"
        png.write_bytes(base64.b64decode(_tiny_png_b64()))

        node = TreeNode(type="leaf", path="x.scriptree", icon="rel-icon.png")
        tool = ToolDef(name="x", executable="echo")
        icon = _resolve_leaf_icon(
            node, tool, tool_dir / "x.scriptree",
        )
        assert not icon.isNull()

    def test_no_icon_sources_returns_null(self, tmp_path):
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef
        node = TreeNode(type="leaf", path="x.scriptree")
        tool = ToolDef(name="x", executable="echo")
        icon = _resolve_leaf_icon(
            node, tool, tmp_path / "x.scriptree",
        )
        # Empty QIcon; addTab() falls back to the no-icon overload.
        assert isinstance(icon, QIcon)
        assert icon.isNull()

    def test_malformed_icon_data_falls_through(self, tmp_path):
        """Invalid base64 should not abort; the helper should
        fall through to the next source."""
        from scriptree.ui.standalone_window import _resolve_leaf_icon
        from scriptree.core.model import TreeNode, ToolDef
        node = TreeNode(
            type="leaf",
            path="x.scriptree",
            icon_data="!!!not-real-base64!!!",
            icon_format="png",
        )
        # No tool icon either -- should return null without raising.
        tool = ToolDef(name="x", executable="echo")
        icon = _resolve_leaf_icon(
            node, tool, tmp_path / "x.scriptree",
        )
        assert icon.isNull()
